version: '3.8'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@user-db:5432/user_db
    depends_on:
      - user-db
    volumes:
      - ./user-service:/app

  hotel-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_db
    ports:
      - "5433:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data

  hotel-service:
    build:
      context: ./hotel-service
    ports:
      - "5001:5001"
    depends_on:
      - hotel-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@hotel-db:5432/hotel_db
    volumes:
      - ./hotel-service:/app

  room-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: room_db
    volumes:
      - room-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  room-service:
    build:
      context: ./room-service
    ports:
      - "5002:5002"
    depends_on:
      - room-db
      - hotel-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@room-db:5432/room_db
      - HOTEL_SERVICE_URL=http://hotel-service:5001/hotels
    volumes:
      - ./room-service:/app

  reservation-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_db
    volumes:
      - reservation-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  reservation-service:
    build:
      context: ./reservation-service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@reservation-db:5432/reservation_db
      - USER_SERVICE_URL=http://user-service:5000/users
      - ROOM_SERVICE_URL=http://room-service:5002/rooms
      - PAYMENT_SERVICE_URL=http://payment-service:5004/payments
    depends_on:
      - reservation-db
      - user-service
      - room-service
      - payment-service

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@payment-db:5432/payment_db
    depends_on:
      - payment-db
    volumes:
      - ./payment-service:/app

  notification-service:
    build: ./notification-service
    ports:
      - "5005:5005"

  hotel-frontend:
    build:
      context: ./frontend-service
    ports:
      - "8080:8080"
    environment:
      - USER_BACKEND_URL=http://user-service:5000
      - HOTEL_BACKEND_URL=http://hotel-service:5001
      - ROOM_BACKEND_URL=http://room-service:5002
      - RESERVATION_BACKEND_URL=http://reservation-service:5003
      - PAYMENT_BACKEND_URL=http://payment-service:5004
    depends_on:
      - user-service
      - hotel-service
      - room-service
      - reservation-service
      - payment-service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  user-data:
  hotel-db-data:
  room-db-data:
  reservation-db-data:
  payment-db-data: