version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@user-db:5432/user_db
    depends_on:
      - user-db
  
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  hotel-service:
    build: ./hotel-service
    ports:
      - "5001:5001"

  room-service:
    build: ./room-service
    ports:
      - "5002:5002"

  reservation-service:
    build: ./reservation-service
    ports:
      - "5003:5003"

  payment-service:
    build: ./payment-service
    ports:
      - "5004:5004"

  notification-service:
    build: ./notification-service
    ports:
      - "5005:5005"

volumes:
  user-data: