version: '3.8'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - hotel-network

  user-service:
    image: user-service:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@user-db:5432/user_db
    depends_on:
      - user-db
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  hotel-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_db
    ports:
      - "5433:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data
    networks:
      - hotel-network

  hotel-service:
    image: hotel-service:latest
    ports:
      - "5001:5001"
    depends_on:
      - hotel-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@hotel-db:5432/hotel_db
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  room-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: room_db
    volumes:
      - room-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - hotel-network

  room-service:
    image: room-service:latest
    ports:
      - "5002:5002"
    depends_on:
      - room-db
      - hotel-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@room-db:5432/room_db
      - HOTEL_SERVICE_URL=http://hotel-service:5001/hotels
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  reservation-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_db
    volumes:
      - reservation-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - hotel-network

  reservation-service:
    image: reservation-service:latest
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@reservation-db:5432/reservation_db
      - USER_SERVICE_URL=http://user-service:5000/users
      - ROOM_SERVICE_URL=http://room-service:5002/rooms
      - PAYMENT_SERVICE_URL=http://payment-service:5004/payments
    depends_on:
      - reservation-db
      - user-service
      - room-service
      - payment-service
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - hotel-network

  payment-service:
    image: payment-service:latest
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@payment-db:5432/payment_db
    depends_on:
      - payment-db
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  notification-service:
    image: notification-service:latest
    ports:
      - "5005:5005"
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  hotel-frontend:
    image: hotel-frontend:latest
    ports:
      - "8085:8085"
    environment:
      - USER_BACKEND_URL=http://user-service:5000
      - HOTEL_BACKEND_URL=http://hotel-service:5001
      - ROOM_BACKEND_URL=http://room-service:5002
      - RESERVATION_BACKEND_URL=http://reservation-service:5003
      - PAYMENT_BACKEND_URL=http://payment-service:5004
    depends_on:
      - user-service
      - hotel-service
      - room-service
      - reservation-service
      - payment-service
    networks:
      - hotel-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hotel-network

  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - hotel-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - hotel-network
    depends_on:
      - user-service
      - room-service
      - hotel-service
      - reservation-service
      - payment-service
      - notification-service

  rsyslog-server:
    image: rsyslog-server:latest
    ports:
      - "515:514/udp"
      - "515:514/tcp"
    networks:
      - hotel-network

volumes:
  user-data:
  hotel-db-data:
  room-db-data:
  reservation-db-data:
  payment-db-data:

networks:
  hotel-network:
